name: Geogebra
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2022.4.26
  - certifi=2022.6.15
  - geos=3.10.2
  - intel-openmp=2021.4.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - numpy=1.22.3
  - numpy-base=1.22.3
  - openssl=1.1.1s
  - pip=22.3.1
  - python=3.9.16
  - python_abi=3.9
  - setuptools=65.6.3
  - shapely=1.8.1
  - six=1.16.0
  - sqlite=3.40.1
  - tzdata=2022g
  - wheel=0.37.1
  - wincertstore=0.2